name: cote_network_logger
description: Beautiful Flutter developer tool for real-time HTTP network monitoring with web dashboard
version: 1.0.2
homepage: https://github.com/thurakhant/cote_network_logger
repository: https://github.com/thurakhant/cote_network_logger
issue_tracker: https://github.com/thurakhant/cote_network_logger/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  # No assets needed for this package

topics:
  - networking
  - debugging
  - http
  - monitoring
  - developer-tools

# Temporarily disabled screenshots until GitHub access is resolved
# screenshots:
#   - description: 'Network Logger Dashboard - Real-time HTTP monitoring'
#     path: screenshots/dashboard.png
#   - description: 'Mobile Integration - Simple setup with beautiful UI'
#     path: screenshots/mobile_demo.png
#   - description: 'Live Demo - App and dashboard working together'
#     path: screenshots/side_by_side.png 