name: cote_network_logger
description: Beautiful Flutter developer tool for real-time HTTP network monitoring with web dashboard
version: 1.0.7
homepage: https://github.com/thurakhant/cote_network_logger
repository: https://github.com/thurakhant/cote_network_logger
issue_tracker: https://github.com/thurakhant/cote_network_logger/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  shelf: ^1.4.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - screenshots/

topics:
  - networking
  - debugging
  - http
  - monitoring
  - developer-tools

screenshots:
  - description: 'Network Logger Dashboard - Real-time HTTP monitoring'
    path: screenshots/dashboard.png
  - description: 'Live Demo - App and dashboard working together'
    path: screenshots/side_by_side.png
  - description: 'Request Details - Detailed request and response inspection'
    path: screenshots/request_details.png 